In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [25]:
import os

# Construct the relative path
relative_path = os.path.join("data/processed", "sales_features.csv")

# Read the processed file to a dataframe
retail_df = pd.read_csv(relative_path)

# Display the first five records 
retail_df.head()

,Customer_ID,age_range,HolidayName,Month_name,jan_dummy,feb_dummy,mar_dummy,apr_dummy,may_dummy,jun_dummy,...,dummy_40_49,dummy_50_59,dummy_60_plus,gender_dummy,HolidayDummy,Max_Temp,Min_Temp,Mean_Temp,Total_Precip_mm,Product_Category
0,CUST015,40-49,0,1,1,0,0,0,0,0,...,1,0,0,0,0,1.8,-5.1,-1.7,0.1,Electronics
1,CUST065,50-59,0,12,0,0,0,0,0,0,...,0,1,0,1,0,3.1,0.3,1.7,0.1,Electronics
2,CUST072,20-29,0,5,0,0,0,0,1,0,...,0,0,0,0,0,19.5,10.0,14.8,0.0,Electronics
3,CUST074,Under 20,0,11,0,0,0,0,0,0,...,0,0,0,0,0,7.1,3.0,5.1,2.8,Beauty
4,CUST089,50-59,0,10,0,0,0,0,0,0,...,0,1,0,0,0,24.8,14.9,19.9,0.0,Electronics

In [26]:
# Describe the dataset
retail_df.describe()

,Month_name,jan_dummy,feb_dummy,mar_dummy,apr_dummy,may_dummy,jun_dummy,jul_dummy,aug_dummy,sep_dummy,...,dummy_30_39,dummy_40_49,dummy_50_59,dummy_60_plus,gender_dummy,HolidayDummy,Max_Temp,Min_Temp,Mean_Temp,Total_Precip_mm
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,994.000000,994.000000,994.000000,994.000000
mean,6.549000,0.078000,0.085000,0.073000,0.086000,0.105000,0.077000,0.072000,0.094000,0.065000,...,0.191000,0.222000,0.221000,0.115000,0.49000,0.030000,14.376157,7.091046,10.735815,2.107143
std,3.452755,0.268306,0.279021,0.260267,0.280504,0.306707,0.266725,0.258617,0.291975,0.246649,...,0.393286,0.415799,0.415128,0.319182,0.50015,0.170673,9.702371,8.399200,8.934392,4.832535
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,-9.300000,-20.500000,-14.900000,0.000000
25%,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,6.100000,0.300000,3.200000,0.000000
50%,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,12.900000,6.600000,9.600000,0.000000
75%,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,24.000000,15.000000,19.600000,1.700000
max,12.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,32.900000,22.400000,26.900000,50.100000

In [27]:
# Info about the fields
retail_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       1000 non-null   object
 1   age_range         1000 non-null   object
 2   HolidayName       1000 non-null   object
 3   Month_name        1000 non-null   int64
 4   jan_dummy         1000 non-null   int64
 5   feb_dummy         1000 non-null   int64
 6   mar_dummy         1000 non-null   int64
 7   apr_dummy         1000 non-null   int64
 8   may_dummy         1000 non-null   int64
 9   jun_dummy         1000 non-null   int64
 10  jul_dummy         1000 non-null   int64
 11  aug_dummy         1000 non-null   int64
 12  sep_dummy         1000 non-null   int64
 13  oct_dummy         1000 non-null   int64
 14  nov_dummy         1000 non-null   int64
 15  dec_dummy         1000 non-null   int64
 16  spend_3m          1000 non-null   int64
 17  QTY_3m            1000 non-null   int64
 18  spend_12m         1000 non-null   int64
 19  QTY_12m           1000 non-null   int64
 20  dummy_under_20    1000 non-null   int64
 21  dummy_20_29       1000 non-null   int64
 22  dummy_30_39       1000 non-null   int64
 23  dummy_40_49       1000 non-null   int64
 24  dummy_50_59       1000 non-null   int64
 25  dummy_60_plus     1000 non-null   int64
 26  gender_dummy      1000 non-null   int64
 27  HolidayDummy      1000 non-null   int64
 28  Max_Temp          994 non-null    float64
 29  Min_Temp          994 non-null    float64
 30  Mean_Temp         994 non-null    float64
 31  Total_Precip_mm   994 non-null    float64
 32  Product_Category  1000 non-null   object
dtypes: float64(4), int64(25), object(4)
memory usage: 257.9+ KB

In [28]:
# Shape 
retail_df.shape

(1000, 33)

In [31]:
# Define the feature variables
features = retail_df.drop(['Customer_ID','age_range', 'HolidayName', 'Month_name',
'Max_Temp', 'Min_Temp', 'Mean_Temp', 'Total_Precip_mm', 'spend_3m','QTY_3m','QTY_12m', 'spend_12m'], axis=1).iloc[:, :-1]
features

,jan_dummy,feb_dummy,mar_dummy,apr_dummy,may_dummy,jun_dummy,jul_dummy,aug_dummy,sep_dummy,oct_dummy,nov_dummy,dec_dummy,dummy_under_20,dummy_20_29,dummy_30_39,dummy_40_49,dummy_50_59,dummy_60_plus,gender_dummy,HolidayDummy
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0
996,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0
997,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
998,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0

In [30]:
# Standardize the spend 
scaler = StandardScaler()
features[[ 'spend_12m']] = scaler.fit_transform(features[['spend_12m']])
features

KeyError: "None of [Index(['spend_12m'], dtype='object')] are in the [columns]"

In [32]:
# Define the target variable
target = retail_df[["Product_Category"]]
target

    Product_Category
0        Electronics
1        Electronics
2        Electronics
3             Beauty
4        Electronics
..               ...
995         Clothing
996         Clothing
997           Beauty
998           Beauty
999      Electronics

[1000 rows x 1 columns]

In [33]:
from sklearn.model_selection import train_test_split

# Divide into test train in the ratio of 4:1
X_train, X_test, y_train, y_test = train_test_split(
    features,
    target,
    test_size=0.2, # 20% of the data is used for testing
    random_state=42 # Providing a value here means getting the same "random" split every time
)

In [34]:
X_train.shape

(800, 20)

In [35]:
y_train

    Product_Category
29          Clothing
535      Electronics
695           Beauty
557           Beauty
836           Beauty
..               ...
106         Clothing
270      Electronics
860      Electronics
435           Beauty
102           Beauty

[800 rows x 1 columns]

In [36]:
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

# Convert target variable to integers 0,1,2 and then convert them to one-hot encoded arrays
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)
print(f'Before one-hot encoding: {y_train[799]}')
y_train = to_categorical(y_train, num_classes=3)
y_test = to_categorical(y_test, num_classes=3)
print(f'After one-hot encoding: {y_train[799]}')

Before one-hot encoding: 0
After one-hot encoding: [1. 0. 0.]

c:\Users\srees\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\srees\miniconda3\envs\dsi_participant\lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [46]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

# Input layer
model.add(Dense(64, activation='relu', input_shape=(20,))) # 64 neurons, ReLU activation, input shape of 21

# Hidden layer
model.add(Dense(64, activation='relu')) # 64 neurons, ReLU activation

# Output layer
model.add(Dense(3, activation='softmax')) # 3 neurons, softmax activation

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 64)                1344

 dense_13 (Dense)            (None, 64)                4160

 dense_14 (Dense)            (None, 3)                 195

=================================================================
Total params: 5,699
Trainable params: 5,699
Non-trainable params: 0
_________________________________________________________________

In [47]:
from tensorflow.keras.optimizers import Adam
model.compile(
    loss='categorical_crossentropy', # Loss function
    optimizer= Adam(learning_rate=0.001), # Optimizer
    metrics=['accuracy'] # Metrics to evaluate the model
)

In [48]:
history = model.fit(
    X_train, # Training data
    y_train, # Training labels
    epochs=100, # Number of epochs
    batch_size=32, # Number of samples per batch
    validation_split=0.2 # Use 20% of the data for validation
)

Epoch 1/100
20/20 [==============================] - 1s 16ms/step - loss: 1.1045 - accuracy: 0.3344 - val_loss: 1.1118 - val_accuracy: 0.3000
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 1.0916 - accuracy: 0.3812 - val_loss: 1.1163 - val_accuracy: 0.3250
Epoch 3/100
20/20 [==============================] - 0s 5ms/step - loss: 1.0829 - accuracy: 0.4062 - val_loss: 1.1164 - val_accuracy: 0.3250
Epoch 4/100
20/20 [==============================] - 0s 5ms/step - loss: 1.0762 - accuracy: 0.4109 - val_loss: 1.1206 - val_accuracy: 0.3125
Epoch 5/100
20/20 [==============================] - 0s 5ms/step - loss: 1.0703 - accuracy: 0.4250 - val_loss: 1.1236 - val_accuracy: 0.3000
Epoch 6/100
20/20 [==============================] - 0s 4ms/step - loss: 1.0656 - accuracy: 0.4328 - val_loss: 1.1301 - val_accuracy: 0.3063
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 1.0590 - accuracy: 0.4453 - val_loss: 1.1307 - val_accuracy: 0.2688
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 1.0536 - accuracy: 0.4625 - val_loss: 1.1367 - val_accuracy: 0.3000
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 1.0479 - accuracy: 0.4656 - val_loss: 1.1363 - val_accuracy: 0.3063
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 1.0447 - accuracy: 0.4688 - val_loss: 1.1470 - val_accuracy: 0.3125
Epoch 11/100
20/20 [==============================] - 0s 4ms/step - loss: 1.0386 - accuracy: 0.4547 - val_loss: 1.1427 - val_accuracy: 0.3000
Epoch 12/100
20/20 [==============================] - 0s 5ms/step - loss: 1.0324 - accuracy: 0.4812 - val_loss: 1.1544 - val_accuracy: 0.3187
Epoch 13/100
20/20 [==============================] - 0s 5ms/step - loss: 1.0283 - accuracy: 0.4750 - val_loss: 1.1543 - val_accuracy: 0.3250
Epoch 14/100
20/20 [==============================] - 0s 5ms/step - loss: 1.0224 - accuracy: 0.4750 - val_loss: 1.1595 - val_accuracy: 0.3187
Epoch 15/100
20/20 [==============================] - 0s 5ms/step - loss: 1.0170 - accuracy: 0.4859 - val_loss: 1.1643 - val_accuracy: 0.3375
Epoch 16/100
20/20 [==============================] - 0s 8ms/step - loss: 1.0165 - accuracy: 0.4734 - val_loss: 1.1655 - val_accuracy: 0.3313
Epoch 17/100
20/20 [==============================] - 0s 5ms/step - loss: 1.0096 - accuracy: 0.4969 - val_loss: 1.1778 - val_accuracy: 0.3187
Epoch 18/100
20/20 [==============================] - 0s 4ms/step - loss: 1.0035 - accuracy: 0.4906 - val_loss: 1.1808 - val_accuracy: 0.3250
Epoch 19/100
20/20 [==============================] - 0s 4ms/step - loss: 1.0003 - accuracy: 0.4922 - val_loss: 1.1796 - val_accuracy: 0.3250
Epoch 20/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9958 - accuracy: 0.5000 - val_loss: 1.1850 - val_accuracy: 0.3438
Epoch 21/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9923 - accuracy: 0.4922 - val_loss: 1.1917 - val_accuracy: 0.3187
Epoch 22/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9860 - accuracy: 0.4891 - val_loss: 1.1977 - val_accuracy: 0.3375
Epoch 23/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9827 - accuracy: 0.5063 - val_loss: 1.2021 - val_accuracy: 0.3438
Epoch 24/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9811 - accuracy: 0.4875 - val_loss: 1.2116 - val_accuracy: 0.3500
Epoch 25/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9788 - accuracy: 0.5234 - val_loss: 1.2087 - val_accuracy: 0.3313
Epoch 26/100
20/20 [==============================] - 0s 5ms/step - loss: 0.9746 - accuracy: 0.5016 - val_loss: 1.2202 - val_accuracy: 0.3375
Epoch 27/100
20/20 [==============================] - 0s 5ms/step - loss: 0.9719 - accuracy: 0.5125 - val_loss: 1.2223 - val_accuracy: 0.3125
Epoch 28/100
20/20 [==============================] - 0s 6ms/step - loss: 0.9642 - accuracy: 0.5109 - val_loss: 1.2228 - val_accuracy: 0.3375
Epoch 29/100
20/20 [==============================] - 0s 5ms/step - loss: 0.9623 - accuracy: 0.5234 - val_loss: 1.2256 - val_accuracy: 0.3187
Epoch 30/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9607 - accuracy: 0.5156 - val_loss: 1.2354 - val_accuracy: 0.3313
Epoch 31/100
20/20 [==============================] - 0s 5ms/step - loss: 0.9585 - accuracy: 0.5328 - val_loss: 1.2334 - val_accuracy: 0.3500
Epoch 32/100
20/20 [==============================] - 0s 6ms/step - loss: 0.9546 - accuracy: 0.5203 - val_loss: 1.2461 - val_accuracy: 0.3313
Epoch 33/100
20/20 [==============================] - 0s 6ms/step - loss: 0.9531 - accuracy: 0.5234 - val_loss: 1.2422 - val_accuracy: 0.3313
Epoch 34/100
20/20 [==============================] - 0s 5ms/step - loss: 0.9532 - accuracy: 0.5297 - val_loss: 1.2492 - val_accuracy: 0.3375
Epoch 35/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9480 - accuracy: 0.5188 - val_loss: 1.2575 - val_accuracy: 0.3375
Epoch 36/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9438 - accuracy: 0.5328 - val_loss: 1.2596 - val_accuracy: 0.3250
Epoch 37/100
20/20 [==============================] - 0s 5ms/step - loss: 0.9408 - accuracy: 0.5328 - val_loss: 1.2645 - val_accuracy: 0.3313
Epoch 38/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9406 - accuracy: 0.5312 - val_loss: 1.2640 - val_accuracy: 0.3438
Epoch 39/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9367 - accuracy: 0.5406 - val_loss: 1.2777 - val_accuracy: 0.3313
Epoch 40/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9351 - accuracy: 0.5391 - val_loss: 1.2754 - val_accuracy: 0.3438
Epoch 41/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9331 - accuracy: 0.5391 - val_loss: 1.2856 - val_accuracy: 0.3063
Epoch 42/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9319 - accuracy: 0.5422 - val_loss: 1.2838 - val_accuracy: 0.3187
Epoch 43/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9302 - accuracy: 0.5344 - val_loss: 1.2955 - val_accuracy: 0.3313
Epoch 44/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9300 - accuracy: 0.5344 - val_loss: 1.2818 - val_accuracy: 0.3500
Epoch 45/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9247 - accuracy: 0.5437 - val_loss: 1.2966 - val_accuracy: 0.3500
Epoch 46/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9263 - accuracy: 0.5453 - val_loss: 1.3007 - val_accuracy: 0.3250
Epoch 47/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9257 - accuracy: 0.5312 - val_loss: 1.3087 - val_accuracy: 0.3375
Epoch 48/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9214 - accuracy: 0.5406 - val_loss: 1.3130 - val_accuracy: 0.3250
Epoch 49/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9192 - accuracy: 0.5328 - val_loss: 1.3110 - val_accuracy: 0.3187
Epoch 50/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9157 - accuracy: 0.5406 - val_loss: 1.3207 - val_accuracy: 0.3562
Epoch 51/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9172 - accuracy: 0.5453 - val_loss: 1.3151 - val_accuracy: 0.3438
Epoch 52/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9145 - accuracy: 0.5453 - val_loss: 1.3211 - val_accuracy: 0.3375
Epoch 53/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9155 - accuracy: 0.5328 - val_loss: 1.3321 - val_accuracy: 0.3438
Epoch 54/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9147 - accuracy: 0.5375 - val_loss: 1.3357 - val_accuracy: 0.3375
Epoch 55/100
20/20 [==============================] - 0s 5ms/step - loss: 0.9082 - accuracy: 0.5500 - val_loss: 1.3481 - val_accuracy: 0.3313
Epoch 56/100
20/20 [==============================] - 0s 5ms/step - loss: 0.9120 - accuracy: 0.5359 - val_loss: 1.3420 - val_accuracy: 0.3250
Epoch 57/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9064 - accuracy: 0.5437 - val_loss: 1.3500 - val_accuracy: 0.3438
Epoch 58/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9062 - accuracy: 0.5547 - val_loss: 1.3494 - val_accuracy: 0.3500
Epoch 59/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9035 - accuracy: 0.5453 - val_loss: 1.3564 - val_accuracy: 0.3438
Epoch 60/100
20/20 [==============================] - 0s 5ms/step - loss: 0.9061 - accuracy: 0.5516 - val_loss: 1.3610 - val_accuracy: 0.3187
Epoch 61/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9081 - accuracy: 0.5484 - val_loss: 1.3590 - val_accuracy: 0.3438
Epoch 62/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9015 - accuracy: 0.5578 - val_loss: 1.3584 - val_accuracy: 0.3688
Epoch 63/100
20/20 [==============================] - 0s 4ms/step - loss: 0.9021 - accuracy: 0.5516 - val_loss: 1.3712 - val_accuracy: 0.3187
Epoch 64/100
20/20 [==============================] - 0s 5ms/step - loss: 0.9012 - accuracy: 0.5547 - val_loss: 1.3801 - val_accuracy: 0.3375
Epoch 65/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8986 - accuracy: 0.5516 - val_loss: 1.3790 - val_accuracy: 0.3375
Epoch 66/100
20/20 [==============================] - 0s 5ms/step - loss: 0.8979 - accuracy: 0.5437 - val_loss: 1.3791 - val_accuracy: 0.3500
Epoch 67/100
20/20 [==============================] - 0s 5ms/step - loss: 0.8959 - accuracy: 0.5594 - val_loss: 1.3791 - val_accuracy: 0.3500
Epoch 68/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8956 - accuracy: 0.5531 - val_loss: 1.3925 - val_accuracy: 0.3438
Epoch 69/100
20/20 [==============================] - 0s 6ms/step - loss: 0.8920 - accuracy: 0.5516 - val_loss: 1.3866 - val_accuracy: 0.3250
Epoch 70/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8948 - accuracy: 0.5469 - val_loss: 1.3882 - val_accuracy: 0.3438
Epoch 71/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8929 - accuracy: 0.5516 - val_loss: 1.4029 - val_accuracy: 0.3250
Epoch 72/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8921 - accuracy: 0.5422 - val_loss: 1.3977 - val_accuracy: 0.3375
Epoch 73/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8909 - accuracy: 0.5531 - val_loss: 1.3952 - val_accuracy: 0.3438
Epoch 74/100
20/20 [==============================] - 0s 5ms/step - loss: 0.8940 - accuracy: 0.5531 - val_loss: 1.4176 - val_accuracy: 0.3250
Epoch 75/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8911 - accuracy: 0.5562 - val_loss: 1.4012 - val_accuracy: 0.3313
Epoch 76/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8929 - accuracy: 0.5375 - val_loss: 1.4148 - val_accuracy: 0.3250
Epoch 77/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8900 - accuracy: 0.5547 - val_loss: 1.4021 - val_accuracy: 0.3313
Epoch 78/100
20/20 [==============================] - 0s 5ms/step - loss: 0.8881 - accuracy: 0.5484 - val_loss: 1.4126 - val_accuracy: 0.3375
Epoch 79/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8886 - accuracy: 0.5469 - val_loss: 1.4222 - val_accuracy: 0.3375
Epoch 80/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8851 - accuracy: 0.5484 - val_loss: 1.4200 - val_accuracy: 0.3500
Epoch 81/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8867 - accuracy: 0.5484 - val_loss: 1.4294 - val_accuracy: 0.3375
Epoch 82/100
20/20 [==============================] - 0s 5ms/step - loss: 0.8863 - accuracy: 0.5484 - val_loss: 1.4184 - val_accuracy: 0.3250
Epoch 83/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8854 - accuracy: 0.5422 - val_loss: 1.4288 - val_accuracy: 0.3250
Epoch 84/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8849 - accuracy: 0.5406 - val_loss: 1.4408 - val_accuracy: 0.3000
Epoch 85/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8863 - accuracy: 0.5437 - val_loss: 1.4389 - val_accuracy: 0.3313
Epoch 86/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8828 - accuracy: 0.5437 - val_loss: 1.4363 - val_accuracy: 0.3438
Epoch 87/100
20/20 [==============================] - 0s 7ms/step - loss: 0.8816 - accuracy: 0.5578 - val_loss: 1.4390 - val_accuracy: 0.3375
Epoch 88/100
20/20 [==============================] - 0s 5ms/step - loss: 0.8824 - accuracy: 0.5484 - val_loss: 1.4481 - val_accuracy: 0.3187
Epoch 89/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8812 - accuracy: 0.5391 - val_loss: 1.4430 - val_accuracy: 0.3313
Epoch 90/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8804 - accuracy: 0.5594 - val_loss: 1.4453 - val_accuracy: 0.3313
Epoch 91/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8782 - accuracy: 0.5516 - val_loss: 1.4589 - val_accuracy: 0.3313
Epoch 92/100
20/20 [==============================] - 0s 4ms/step - loss: 0.8817 - accuracy: 0.5406 - val_loss: 1.4456 - val_accuracy: 0.3250
Epoch 93/100
20/20 [==============================] - 0s 5ms/step - loss: 0.8793 - accuracy: 0.5641 - val_loss: 1.4514 - val_accuracy: 0.3187
Epoch 94/100
20/20 [==============================] - 0s 6ms/step - loss: 0.8764 - accuracy: 0.5516 - val_loss: 1.4577 - val_accuracy: 0.3063
Epoch 95/100
20/20 [==============================] - 0s 7ms/step - loss: 0.8777 - accuracy: 0.5406 - val_loss: 1.4590 - val_accuracy: 0.3125
Epoch 96/100
20/20 [==============================] - 0s 7ms/step - loss: 0.8809 - accuracy: 0.5516 - val_loss: 1.4591 - val_accuracy: 0.3375
Epoch 97/100
20/20 [==============================] - 0s 7ms/step - loss: 0.8767 - accuracy: 0.5531 - val_loss: 1.4640 - val_accuracy: 0.3375
Epoch 98/100
20/20 [==============================] - 0s 7ms/step - loss: 0.8757 - accuracy: 0.5562 - val_loss: 1.4554 - val_accuracy: 0.3313
Epoch 99/100
20/20 [==============================] - 0s 7ms/step - loss: 0.8787 - accuracy: 0.5562 - val_loss: 1.4626 - val_accuracy: 0.3125
Epoch 100/100
20/20 [==============================] - 0s 7ms/step - loss: 0.8762 - accuracy: 0.5500 - val_loss: 1.4720 - val_accuracy: 0.3375